services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/blog_escolar?schema=public
    depends_on:
      - db
    volumes:
      - .:/usr/app
    command: sh -c "npx prisma migrate deploy && yarn start"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_escolar
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
